### ISSUE TITLE
CSS 实现优惠券的技巧

### ISSUE THREAD

**Issue by xiaodongxier** [xiaodongxier/iWebs#112]
![](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/67f729c401c34192b314771cd610b603~tplv-k3u1fbpfcp-watermark.image)

> 本文作者：严文彬

> 原创声明：本文为阅文前端团队 YFE 成员出品，请尊重原创，转载请联系公众号 (id: yuewen_YFE) 获取授权，并注明作者、出处和链接。

在实际 Web 开发过程中，总会遇到各种各样的布局。有公司同事问我这样一种布局有没有什么好的实现方式，就是一种在活动充值页非常普遍的优惠券效果，如下

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f0c1da3302004cd0a7205eb9efd94839~tplv-k3u1fbpfcp-zoom-1.image)

还有这样的

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b272ec7e03aa4692b92cca94fd31e84a~tplv-k3u1fbpfcp-zoom-1.image)

考虑到各种可能出现的场景，抽象出以下几种案例，一起来看看实现吧

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/6d740ae184484a968bbb00ed6f5ef21b~tplv-k3u1fbpfcp-zoom-1.image)

## 一、最佳实现方式

首先，碰到这类布局的最佳实现肯定是[mask 遮罩](https://developer.mozilla.org/zh-CN/docs/Web/CSS/mask?fileGuid=fKc3ePJfifoZewha)。关于遮罩，可以看一下[CSS3 Mask 安利报告](https://jelly.jd.com/article/6006b1045b6c6a01506c87bb?fileGuid=fKc3ePJfifoZewha)。这里简单介绍一下

基本语法很简单，和**background**的语法基本一致

```css
.content{
  -webkit-mask: '遮罩图片' ;
}

.content{
  -webkit-mask: '遮罩图片' [position] / [size] ;
}
```

这里的遮罩图片和背景的使用方式基本一致，可以是**PNG 图片**、**SVG 图片**、也可以是**渐变绘制**的图片，同时也支持**多图片叠加**。

遮罩的原理很简单，**最终效果只显示不透明的部分，透明部分将不可见，半透明类推**

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3e5bb8ccbded457e985db7ad1d564c59~tplv-k3u1fbpfcp-zoom-1.image)

> 事实上，除了根据透明度（Alpha）来作为遮罩条件，还可以通过亮度（luminance）来决定，比如白色表示隐藏，黑色表示可见。不过目前只有 Firefox 支持

所以，只要能绘制以上各种形状，就可以实现了。

## 二、内凹圆角

优惠券大多有一个很明显的特点，就是**内凹圆角**。提到圆角，很容易想到[radial-gradient](https://developer.mozilla.org/zh-CN/docs/Web/CSS/radial-gradient()?fileGuid=fKc3ePJfifoZewha)。这个语法有点复杂，记不住没关系，可以看看张老师的这篇[10 个 demo 示例学会 CSS3 radial-gradient 径向渐变](https://www.zhangxinxu.com/wordpress/2017/11/css3-radial-gradient-syntax-example/?fileGuid=fKc3ePJfifoZewha)。

```css
.content{
  -webkit-mask: radial-gradient(circle at left center, transparent 20px, red 20px); 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7b15a32f51134672bd5ed4e829f6816c~tplv-k3u1fbpfcp-zoom-1.image)

这样就绘制了一个半径为 20px 的透明的圆，不过代码层面还有很多优化的空间。

1.  在实现边界分明的渐变时，后面颜色的位置只需要小于等于前面颜色的位置就行了，比如**0**
2.  透明颜色可以用**16 进制**缩写比如\*\*#0000**来代替**，**不透明的部分随便用一个颜色就好，我喜欢用**red\*\*，主要是这个单词比较短
3.  还有渐变的位置默认是居中的，所以第二个 center 可以去除，left 可以用**0**来表示

进一步简化就得到了

```css
.content{
  -webkit-mask: radial-gradient(circle at 0, #0000 20px, red 0); 
}
```

不错，又少了好几个 B 的流量~ 可以查看在线实例[codepen 优惠券实现 1](https://codepen.io/xboxyan/pen/BaQXQXB?fileGuid=fKc3ePJfifoZewha)

## 三、优惠券效果

上面是一个最基本的内凹圆角效果，现在来实现下面几种布局，比如两个半圆的，根据上面的例子，再复制一个圆不就可以了？改一下定位的方向

```css
.content{
  -webkit-mask: radial-gradient(circle at 0, #0000 20px, red 0), radial-gradient(circle at right, #0000 20px, red 0); 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3469ba7ab1b94e46852fbd6ce74c2164~tplv-k3u1fbpfcp-zoom-1.image)

这时发现一个圆都没有了。原因其实很简单，如下演示，**两层背景相互叠加，导致整块背景都成了不透明的**，所以 mask 效果表现为全部可见。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1759b6a6937f4f1cb277ecb1d266e944~tplv-k3u1fbpfcp-zoom-1.image)

解决方式有 2 个，分别是：

1.  **把两个凹角的地方错开，这里可以通过修改尺寸和位置，同时还需要禁止平铺**

```css
.content{
-webkit-mask: radial-gradient(circle at 0, #0000 20px, red 0), radial-gradient(circle at right, #0000 20px, red 0);
-webkit-mask-size: 51%; 
-webkit-mask-position: 0, 100%; 
-webkit-mask-repeat: no-repeat;
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/2820f5e92a4243f785ded5c052c89abb~tplv-k3u1fbpfcp-zoom-1.image)

动态演示如下，这样就不会互相覆盖了

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/18d270df14ae4577946083bad3106c6c~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 2](https://codepen.io/xboxyan/pen/WNoVjmb?fileGuid=fKc3ePJfifoZewha)

2.  **使用遮罩合成**[mask-composite](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-composite?fileGuid=fKc3ePJfifoZewha)**，这个可能不太熟悉，简单介绍一下**

标准属性下**mask-composite**有 4 个属性值（Firefox 支持）

```css

mask-composite: add; 
mask-composite: subtract; 
mask-composite: intersect; 
mask-composite: exclude; 
```

这个可能有些不好理解，其实可以参考一些图形软件的形状合成操作，比如 photoshop

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/a24631564d6547d8bb62637cdc59ea7d~tplv-k3u1fbpfcp-zoom-1.image)

[-webkit-mask-composite](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-composite?fileGuid=fKc3ePJfifoZewha)与标准下的值有所不同，属性值非常多，看下面

```css
-webkit-mask-composite: clear; 
-webkit-mask-composite: copy; 
-webkit-mask-composite: source-over; 
-webkit-mask-composite: source-in; 
-webkit-mask-composite: source-out; 
-webkit-mask-composite: source-atop;
-webkit-mask-composite: destination-over;
-webkit-mask-composite: destination-in; 
-webkit-mask-composite: destination-out;
-webkit-mask-composite: destination-atop;
-webkit-mask-composite: xor; 
```

是不是一下就懵了？不用慌，可以看到上面有几个值是**source-**\*，还有几个是\*\*destination-\*\*\*开头的，**source 代表新内容**，也就是上面绘制的图层，**destination 代表元内容**，也就是下面绘制的图层（**在 CSS 中，前面的图层会覆盖后面的图层**），这里的属性值其实是借用了 Canvas 中的概念，具体可以查看[CanvasRenderingContext2D.globalComposite](https://www.canvasapi.cn/CanvasRenderingContext2D/globalCompositeOperation?fileGuid=fKc3ePJfifoZewha)

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b6294063c5a64e5889714e72f687cf9c~tplv-k3u1fbpfcp-zoom-1.image)

记不住没关系，实际开发可以逐一试验\[\\捂脸]。具体差异可以查看[codepen -webkit-mask-composite 属性值演示](https://codepen.io/xboxyan/pen/RwKbGwN?fileGuid=fKc3ePJfifoZewha)

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/19f2657a9169441fb5f870e8e59fb8ff~tplv-k3u1fbpfcp-zoom-1.image)

了解这个属性后，上面的叠加问题就很简单了，设置**只显示重合的地方**就行了

```css
.content{
  -webkit-mask: radial-gradient(circle at 0, #0000 20px, red 0), radial-gradient(circle at right, #0000 20px, red 0); 
  -webkit-mask-composite: source-in | destination-in ; 
  mask-composite: intersect; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ba7a41090aea4deb8695eec37c96fb06~tplv-k3u1fbpfcp-zoom-1.image)

动态演示如下，这样只会显示**互相重合的地方**

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/745518f635964f339387cb59391f868c~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 3](https://codepen.io/xboxyan/pen/rNWXmbm?fileGuid=fKc3ePJfifoZewha)

2 个圆角的实现了，4 个的就很容易了，画 4 个圆就行，同样利用遮罩合成可以轻易实现

```css
content{
  -webkit-mask: radial-gradient(circle at 0 0, #0000 20px, red 0), radial-gradient(circle at right 0, #0000 20px, red 0), radial-gradient(circle at 0 100%, #0000 20px, red 0), radial-gradient(circle at right 100%, #0000 20px, red 0); 
  -webkit-mask-composite: source-in | destination-in ; 
  mask-composite: intersect; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/8b1a85cc170f4dfa8fd01f42d4af9367~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 4](https://codepen.io/xboxyan/pen/jOVgwOq?fileGuid=fKc3ePJfifoZewha)

## 四、优惠券平铺效果

上面的例子展示了 2 个圆角和 4 个圆角的效果，分别绘制了 2 个和 4 个圆，其实这是可以通过平铺来实现的，只需要一个圆就可以。实现步骤如下

1.  **画一个左中的靠边的透明圆**

```css
.content{
  -webkit-mask: radial-gradient(circle at 20px, #0000 20px, red 0); 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/4df9811251c9485fa25273de0bad3292~tplv-k3u1fbpfcp-zoom-1.image)

2.  **向左平移自身的一半**

```css
.content{
  -webkit-mask: radial-gradient(circle at 20px, #0000 20px, red 0); 
  -webkit-mask-position: -20px
}

.content{
  -webkit-mask: radial-gradient(circle at 20px, #0000 20px, red 0) -20px; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/629259f3b8ca4eacbd56785de787909e~tplv-k3u1fbpfcp-zoom-1.image)

效果就出来了，是不是很神奇？其实就是利用到了默认的**repeat 特性**，这里用一张动图就能明白了

> 下面**红色边框内表示视区范围**，也就是最终的效果，这里为了演示，把视线之外的**平铺**做了半透明处理，移动表示 position 改变的过程

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b53ef019d3804b71a66a4488ee39c066~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 5](https://codepen.io/xboxyan/pen/MWbNozQ?fileGuid=fKc3ePJfifoZewha)

同样原理，4 个圆角也可以采用这种方式实现

```css
.content{
  -webkit-mask: radial-gradient(circle at 20px 20px, #0000 20px, red 0); 
  -webkit-mask-position: -20px -20px;
}

.content{
  -webkit-mask: radial-gradient(circle at 20px 20px, #0000 20px, red 0) -20px -20px; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ee1376b457844f9390a2d6f1c45ea416~tplv-k3u1fbpfcp-zoom-1.image)

实现原理演示如下

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/05e41d4d58dd4b9bb1b11af9a1c99e0b~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 6](https://codepen.io/xboxyan/pen/mdONMwR?fileGuid=fKc3ePJfifoZewha)

6 个圆角就需要改一下平铺尺寸了。

```css
.content{
  -webkit-mask: radial-gradient(circle at 20px 20px, #0000 20px, red 0); 
  -webkit-mask-position: -20px -20px;
  -webkit-mask-size: 50%;
}

.content{
  -webkit-mask: radial-gradient(circle at 20px 20px, #0000 20px, red 0) -20px -20px / 50%; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/0990fa22ba4741399525680ce66acc68~tplv-k3u1fbpfcp-zoom-1.image)

实现原理演示如下

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/5745f206eadb4b1ab14e233777c36e2b~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 7](https://codepen.io/xboxyan/pen/PobMKyE?fileGuid=fKc3ePJfifoZewha)

如果继续缩小背景图的尺寸，还可以得到最后的效果

```css
.content{
  -webkit-mask: radial-gradient(circle at 10px, #0000 10px, red 0); 
  -webkit-mask-position: -10px;
  -webkit-mask-size: 100% 30px;
}

.content{
  -webkit-mask: radial-gradient(circle at 20px 20px, #0000 20px, red 0) -10px / 100% 30px; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/761e37382176444a8d0b7e715439f386~tplv-k3u1fbpfcp-zoom-1.image)

实现原理演示如下，其实就平铺

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/05f720725e71437ea81899c6cb294b1f~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 8](https://codepen.io/xboxyan/pen/zYogbQJ?fileGuid=fKc3ePJfifoZewha)

## 五、反向镂空叠加

有些情况下可能单一的一层渐变绘制不了很复杂的图形，这就需要用到反向镂空技术了，其实就是上面提到过的**遮罩合成**，这里再运用一下

1.  **先把上面的实现拿过来**

```css
.content{
  -webkit-mask: radial-gradient(circle at 20px 20px, #0000 20px, red 0) -20px -20px / 50%; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/8091c9b608c64a0580e98a8efdacd283~tplv-k3u1fbpfcp-zoom-1.image)

2.  **直接在这个基础上打一排小洞**

```css
.content{
  -webkit-mask: radial-gradient( circle at 50%, red 5px, #0000 0) 50% 50% / 100% 20px, radial-gradient(circle at 20px 20px, #0000 20px, red 0) -20px -20px / 50%;
  -webkit-mask-composite: destination-out;
  mask-composite: subtract; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b1166e3e5a134328aad77c467da7f846~tplv-k3u1fbpfcp-zoom-1.image)

注意这里用到了\*\*-webkit-mask-composite: destination-out\*\*，**表示减去，只显示下方遮罩，重合的地方不显示**

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/51b69328c64e49aa966ad2d97c6b362e~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 9](https://codepen.io/xboxyan/pen/vYyoMoZ?fileGuid=fKc3ePJfifoZewha)

也可以放在两边，改一下**position**就可以了

```css
.content{
  -webkit-mask: radial-gradient( circle at 5px, red 5px, #0000 0) -5px 50% / 100% 20px, radial-gradient(circle at 20px 20px, #0000 20px, red 0) -20px -20px / 50%;
  -webkit-mask-composite: destination-out;
  mask-composite: subtract; 
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/890ef27c1b104061b3fede8cd30ae1d4~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen 优惠券实现 10](https://codepen.io/xboxyan/pen/BaQXeNV?fileGuid=fKc3ePJfifoZewha)

## 六、边框遮罩

有些同学觉得**径向渐变太复杂，实在是写不出来，能不能用图片代替呢**？其实也是可行的。这里说的边框遮罩指的是[mask-border](https://www.w3.org/TR/css-masking-1/#mask-borders?fileGuid=fKc3ePJfifoZewha), 目前还在 W3C 草案当中，不过有一个替代属性[-webkit-mask-box-image](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-box-image?fileGuid=fKc3ePJfifoZewha)

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c42470a8a1c74b6cae151307d1679ae0~tplv-k3u1fbpfcp-zoom-1.image)

语法和概念和[border-image](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image?fileGuid=fKc3ePJfifoZewha)非常相似，关于**border-image**可参考这篇文章[border-image 的正确用法](https://jelly.jd.com/article/6006b1045b6c6a01506c87bc?fileGuid=fKc3ePJfifoZewha)，这里主要了解一下用法和效果

```css
.content{
  -webkit-mask-box-image: '遮罩图片' [<top> <right> <bottom> <left> <x-repeat> <y-repeat>]
}
```

比如有一张这样的图片

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/eb1ae763e8a24aa9ab43503c99d9fe95~tplv-k3u1fbpfcp-zoom-1.image)

SVG 代码长这样，很多工具都可以导出来，实在不会可以直接找设计同学

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="60.031" height="60.031" viewBox="0 0 60.031 60.031"><path d="M40 60.027H20.129A20.065 20.065 0 0 0 .065 40H0V20.127h.065A20.066 20.066 0 0 0 20.131.061v-.065H40v.065a20.065 20.065 0 0 0 20.027 20.064V40A20.063 20.063 0 0 0 40 60.027z" fill-rule="evenodd"/></svg>
```

这里需要转义一下，可借助张老师的[SVG 在线合并工具](https://www.zhangxinxu.com/sp/svgo/?fileGuid=fKc3ePJfifoZewha)

```css
.content{
  -webkit-mask-box-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='60.031' height='60.031' viewBox='0 0 60.031 60.031'%3E%3Cpath d='M40 60.027H20.129A20.065 20.065 0 0 0 .065 40H0V20.127h.065A20.066 20.066 0 0 0 20.131.061v-.065H40v.065a20.065 20.065 0 0 0 20.027 20.064V40A20.063 20.063 0 0 0 40 60.027z' fill-rule='evenodd'/%3E%3C/svg%3E") 20;
  
}
```

然后就实现了这样一个形状，同样是自适应的

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c1f1ff835e384f71a82e3868b52c5a10~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen -webkit-mask-box-iamge 实现 1](https://codepen.io/xboxyan/pen/oNBvZmb?fileGuid=fKc3ePJfifoZewha)

再比如有一张这样的图片

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/e307f65e69cf450bb4e7976e1f3bbda9~tplv-k3u1fbpfcp-zoom-1.image)

```css
.content{
  -webkit-mask-box-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='60.031' height='60.031' viewBox='0 0 60.031 60.031'%3E%3Cpath d='M55.186 30.158a4.965 4.965 0 0 0 4.841 4.959V40A20.063 20.063 0 0 0 40 60.027H20.129A20.065 20.065 0 0 0 .065 40H0v-4.888c.054 0 .1.016.158.016a4.973 4.973 0 1 0 0-9.945c-.054 0-.1.014-.158.015v-5.074h.065A20.066 20.066 0 0 0 20.131.058v-.065H40v.065a20.065 20.065 0 0 0 20.027 20.064v5.07a4.965 4.965 0 0 0-4.841 4.966z' fill-rule='evenodd'/%3E%3C/svg%3E") 20;
}
```

可以得到这样一个形状，两侧的半圆被拉伸了

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b6b880cbbe134ee392ef613255b4ad87~tplv-k3u1fbpfcp-zoom-1.image)

这时只需要设置平铺方式\*\*-webkit-mask-box-image-repeat ,\*\*这个和[border-image-repeat](https://developer.mozilla.org/zh-CN/docs/Web/CSS/border-image-repeat?fileGuid=fKc3ePJfifoZewha)是一样的概念，有以下 4 个值

```css
-webkit-mask-box-image-repeat: stretch; 
-webkit-mask-box-image-repeat: repeat; 
-webkit-mask-box-image-repeat: round; 
-webkit-mask-box-image-repeat: space; 
```

几种平铺方式的差异如下

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/969db0388c3e420fb3858895305e68dd~tplv-k3u1fbpfcp-zoom-1.image)

这里我们可以采用**round**或者**repeat**

```css
.content{
  -webkit-mask-box-image: url("...") 20;
  -webkit-mask-box-image-repeat: round;
}
```

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/de049448aabd4533ae953d6d8ad58878~tplv-k3u1fbpfcp-zoom-1.image)

可以查看在线实例[codepen -webkit-mask-box-iamge 实现 2](https://codepen.io/xboxyan/pen/gOgYWej?fileGuid=fKc3ePJfifoZewha)

## 七、总结和说明

以上一共介绍了 12 种绘制优惠券的案例，应该可以解决掉绝大部分这类布局的问题，这里总结以下几点

1.  **CSS mask**一定是这类布局最完美的实现方式
2.  需要**CSS radial-gradient**绘制图形的技巧
3.  尽可能采用**repeat**来重复相同的元素
4.  多种形状叠加时需要灵活运用**mask-composite**
5.  也可以采用图片来代替 CSS 渐变，需要使用**mask-border**

关于兼容性，其实不考虑 IE 都没有什么大问题，最后的 mask-border 目前只兼容 chrome 内核，移动端可放心使用

感谢阅读，希望能对日后的工作有所启发。 
 [https://juejin.cn/post/6945023989555134494?utm_source=gold_browser_extension](https://juejin.cn/post/6945023989555134494?utm_source=gold_browser_extension)
