### ISSUE TITLE
CSS实现阮大佬博文的阅读进度功能 - 掘金

### ISSUE THREAD

**Issue by xiaodongxier** [xiaodongxier/iWebs#141]
「这是我参与 11 月更文挑战的第 23 天，活动详情查看：[2021 最后一次更文挑战](https://juejin.cn/post/7023643374569816095/ "https&#x3A;//juejin.cn/post/7023643374569816095/")」

## 🎄 前言

小包在学习阮一峰大佬的《ES6 入门教程》时，对文章顶部的**阅读进度**功能产生了浓厚的兴趣。小包当时猜想应该是使用 `JavaScript` 实现的，但最近爱上了浩如烟海的 `CSS` ，于是小包有个大胆的想法，单纯的 `CSS` 能实现阅读进度功能吗？

能，不止能，还非常巧妙！`CSS⭐CSS⭐CSS` 真的太强了。

虽然通过 `CSS` 可以实现阅读进度问题，但 `JavaScript` 作为老本行，一样得精通。

因此学习本文，你可以学会:

-   使用 `JavaScript` 实现阅读进度功能
-   使用 `CSS` 实现阅读进度功能

### 📃 HTML 与 CSS

`html css` 部分非常简单，通过嵌套的两个 `div` 实现，外部的 `div` 提供底色背景，内部 `div` 显示阅读进度

```html
<div class="read_pro">
    <div class="read_pro_inner"></div>
</div>
```

```css
.read_pro {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 3px;
    background-color: #DDD;
}
.read_pro_inner {
    content: '';
    position: absolute;
    left: 0;
    height: 100%;
    background-color: #0089f2;
}
```

当我们设置 `.read_pro_inner` 的宽度为 `20%` 时，得到的效果图如下:

![](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7f32021117fc4d2ca9c7eda0471be9c7~tplv-k3u1fbpfcp-watermark.awebp?)

> 只截取部分图，并放大了浏览器，要不灰色部分会非常长

台子搭好了，下面就是通过 `js` 来动态计算 `read_pro_inner` 的 `width` 即可。

### 🎬 JS 实现

如果我们利用 `JavaScript` 来实现阅读进度，我们要获取到文档的总高度、文档滚动距离、浏览器窗口的可视高度。

-   文档总高度: `document.documentElement.scrollHeight`
-   窗口可视高度: `document.documentElment.cliengHeight`
-   滚动距离: `document.documentElement.scrollTop || document.body.scrollTop`

光看上面三个属性的名字有几分难以理解，来看一张示意图

![](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/12b3dca3aef34cbdbb9cb44c83e21526~tplv-k3u1fbpfcp-watermark.awebp?)

从上图可以看到 `scrollTop` 就是已经读过被卷起来的文档部分，`scrollHeight` 是文档的总长度，`clientHeight` 是浏览器显示区域的高度

> 图源: [慕课手记](https://www.imooc.com/article/17571 "https&#x3A;//www.imooc.com/article/17571")

获取上面几个属性值后，阅读进度就可以通过下面的公式计算出来

```js
readProInner.style.width = +(scrollTop / (scrollHeight- clientHeight)).toFixed(2)*100 + '%'
```

**大家可能会有疑惑，为什么分母是 `scrollHeight- clientHeight` 而不是 `scrollHeight`?**

当滚动条滚动到底部时，浏览器此时仍显示一屏内容，此时滚动条无法再滚动，`scrollTop` 无法再增加，因此 `scrollTop` 的最大值是 `scrollHeight- clientHeight` ，如果使用 `scrollHeight` 做分母，阅读进度最终无法达到 `100%`。

```js
document.addEventListener('scroll', function(e) {
    const scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
    readProInner.style.width = +(scrollTop/(scrollHeight-clientHeight)).toFixed(2)*100 + '%'
})
```

使用 `js` 实现需要监听 `scroll` 事件，而且滚动时有可能是频繁的 `scroll` 事件触发，有可能会造成一定的性能浪费，所以我们来一起学习 `css` 实现方案

## 🌟 使用 CSS 实现阅读进度

使用 `CSS` 实现阅读进度的方法很有意思，而且非常巧妙，不多说了，一起来看看。

### 📕预备知识

1.  `linear-gradient`: 线性渐变，第一个参数为渐变方向，后面是颜色比例变化。

    比如设置 `linear-gradient(to right top, #0089f2 50%, #DDD 50%)`

    就可以实现下面效果，一个蓝色的三角形:

    ![](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/d88bc29ebd674eb4b7302c77639a0fd6~tplv-k3u1fbpfcp-watermark.awebp?)

    看到这种蓝色的三角形，你有没有感觉离阅读进度已经很近了？

    如果我们用一块白块遮住蓝块，只留一条缝在顶部，那当前显示出来蓝色块的底边不就是阅读进度吗？

    ![](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/2db4d5131c0e403bafccb8a96411b849~tplv-k3u1fbpfcp-watermark.awebp?)

    最后处理最后一屏的问题，保证滚动条滚动至底部时，阅读进度到达 `100%`

    ![](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/75c6b558d2814cb4a58ab713a78ec3b0~tplv-k3u1fbpfcp-watermark.awebp?)

    > 这里如果没能理解原理，不用急，后面我会更详细的演示
2.  `@supports`

类似于 `js` 的功能检查，可以检查 `CSS` 中某一属性或功能当前浏览器是否支持。

### 💡 实现原理

上面讲解 `linear-height` 时，我们提出了一种实现方案: 使用一块白块遮住蓝块，只留一条缝在顶部，显示的蓝条长度就是阅读进度

光说不难假把式，为了方便大家理解原理，我们使用一个案例来模拟一下，蓝块仍保持原来大小，使用一块 `0.8` 透明度的黑块盖在上面，黑块给蓝块在顶部空出 `10px` 空间。具体看下面演示

![](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/41a1af97d8264a95934b08fac4a99f70~tplv-k3u1fbpfcp-watermark.awebp?)

现在是不是感觉瞬间茅塞顿开

### 💻 CSS 实现

1.  首先使用 `linear-gradient` 实现蓝色背景块，并且要空出最后一屏

```css
body{	
    background: linear-gradient(to right top, #0089f2 50%, #DDD 50%);
    
    
    background-size: 100% calc(100% - 100vh + 4px);
    background-repeat: no-repeat;
}

```

2.  设置盖住蓝块的白块

阅读进度条的高度为 `3px` ，因此设置白块的高度为 `100% - 3px`，可以另外加一个 `div` 元素来设置白块，但小包推荐使用为元素 `:before/:after` ，伪元素不在文档流之中，方便渲染和控制

```css
body:before{
    content:'';
    
    position: fixed;
    
    
    top: 3px;
    bottom: 0;
    width: 100%;
    
    z-index: -1;
    background: white;
}
```

通过上面简单的代码，就可以实现封面阅读进度效果了，撒花~~~~

## 🛕 源码仓库

传送门: [阅读进度功能](https://github.com/zcxiaobao/zc-demos/tree/main/display/%E9%98%85%E8%AF%BB%E8%BF%9B%E5%BA%A6 "https&#x3A;//github.com/zcxiaobao/zc-demos/tree/main/display/%E9%98%85%E8%AF%BB%E8%BF%9B%E5%BA%A6")

如果感觉有帮助的话，别忘了给小包点个 ⭐ 。

## 💘 往期精彩文章

-   [牛客最新前端 JS 笔试百题](https://juejin.cn/post/7023271065392513038#heading-38 "https&#x3A;//juejin.cn/post/7023271065392513038#heading-38")
-   [牛客最新前端面经面试题汇总 (含解析)](https://juejin.cn/post/7028478428680552456 "https&#x3A;//juejin.cn/post/7028478428680552456")
-   [CSS 实现一只自由飞翔的鸟儿🐦](https://juejin.cn/post/7032876592544088101 "https&#x3A;//juejin.cn/post/7032876592544088101")
-   [抓取牛客最新前端面试题五百道 数据分析 JS 面试热点](https://juejin.cn/post/7022799579087110181 "https&#x3A;//juejin.cn/post/7022799579087110181")
-   [给 VSCode 和网站领养喵咪 一起快乐撸猫](https://juejin.cn/post/7026910973663379470 "https&#x3A;//juejin.cn/post/7026910973663379470")
-   [原生 JavaScript 灵魂拷问 (一)，你能答上多少？](https://juejin.cn/post/7021750693262262308 "https&#x3A;//juejin.cn/post/7021750693262262308")
-   [JavaScript 之彻底理解原型与原型链](https://juejin.cn/post/6844903780278861838 "https&#x3A;//juejin.cn/post/6844903780278861838")
-   [JavaScript 之彻底理解 EventLoop](https://juejin.cn/post/7020328988715270157 "https&#x3A;//juejin.cn/post/7020328988715270157")
-   [《2w 字大章 38 道面试题》彻底理清 JS 中 this 指向问题](https://juejin.cn/post/7019470820057546766 "https&#x3A;//juejin.cn/post/7019470820057546766")
-   参考链接: [juejin.cn/post/691163…](https://juejin.cn/post/6911636545074102279 "https&#x3A;//juejin.cn/post/6911636545074102279") [codepen.io/MadeByMike/…](https://codepen.io/MadeByMike/pen/ZOrEmr "https&#x3A;//codepen.io/MadeByMike/pen/ZOrEmr")

## 💥 后语

伙伴们，如果大家感觉本文对你有一些帮助，给阿包点一个赞👍或者关注➕都是对我最大的支持。

另外如果本文章有问题，或者对文章其中一部分不理解，都可以评论区回复我，我们来一起讨论，共同学习，一起进步！

如果感觉评论区说不明白，也可以添加我的微信 (li444186976) 或者 qq(3315161861) 详细交流，名字都是战场小包。 
 [https://juejin.cn/post/7033668584026931214](https://juejin.cn/post/7033668584026931214)
